#!/usr/bin/env bash

# TODO move me
source "$HOME"/dev/meta/configs/scripts/m.lib/lib.mxtrap.sh

# if tty -s; then mlg interactive; else mlg none-intreractive;fi

 MXC_V='mxc-v1.3'                         ; export MXC_V

MXBASE=$HOME/dev/meta/configs/scripts/MXX ; export MXBASE
MXDIST=$XDG_CONFIG_HOME/mxc               ; export MXDIST
MXTEMP=$MXBASE/dist                       ; export MXTEMP
MXSNAP=$MXBASE/snapshots                  ; export MXSNAP

MTHEME=$MXTEMP/theme.mx                   ; export MTHEME
OTHEME=$MXDIST/theme.mx                   ; export OTHEME

M_SEED=$MXTEMP/mx-seed                    ; export M_SEED
O_SEED=$MXDIST/mx-seed                    ; export O_SEED

mkdir "$MXDIST" -p 2>/dev/null || true 
mkdir "$MXTEMP" -p 2>/dev/null || true 
mkdir "$MXSNAP" -p 2>/dev/null || true 

XSEED=$MXBASE/src/xseed.sh
XANSI=$MXBASE/src/xansi.sh

PAINT=$MXBASE/src/paint.sh
XDEMO=$MXBASE/src/xdemo.sh
XMENU=$MXBASE/src/xmenu.sh
XGENC=$MXBASE/src/xgenc.sh
CALIB=$MXBASE/src/calib.sh
XSNAP=$MXBASE/src/snaps.sh

X_OUT=$MXBASE/src/x_out.sh

# X_KIT=$MXBASE/src/plugins/mx-kit.sh
# X_XRS=$MXBASE/src/plugins/mx-xrs.sh
# X_VIM=$MXBASE/src/plugins/mx-vim.sh
# X_SPT=$MXBASE/src/plugins/mx-spt.sh
# X_GTK=$MXBASE/src/plugins/mx-gtk.sh
# X_CHR=$MXBASE/src/plugins/mx-chr.sh
# X_FZF=$MXBASE/src/plugins/mx-fzf.sh

##########
. "$PAINT"
. "$XDEMO"
. "$XMENU"
# .........
. "$MXBASE"/plugins/9-awm.sh
. "$MXBASE"/plugins/2-tmux.sh
###########
# \\\\\\\\\\\\\\\\\\\\\\\\\\\\  
################################
#  ............................ .........................................#
ClearTemp     () { Info ' Cleaning temp'           ; rm "$MXTEMP"/*         || { Info "empty dir    " 2 && echo "$MXTEMP"            ; } }
#  ............................ .........................................#
SaveSeed      () { Info " Save Temp Seed  $XSEED"  ; . "$XSEED"             || { Info "missing file " 1 && echo "$XSEED"   && exit 1 ; } }
SaveTheme     () { Info " Save Temp Theme $X_OUT"  ; . "$X_OUT"             || { Info "missing file " 1 && echo "$X_OUT"   && exit 1 ; } }
#  ............................ .........................................#
ReleaseSeed   () { Info " Release Seed  $O_SEED" 0 ; cp "$M_SEED" "$O_SEED" || { Info "missing file " 1 && echo "$M_SEED"  && exit 1 ; } }
ReleaseTheme  () { Info " Release Theme $OTHEME" 0 ; cp "$MTHEME" "$OTHEME" || { Info "missing file " 1 && echo "$MTHEME"  && exit 1 ; } }
#  ............................ .........................................#
LoadTempTheme () { Info ' Load Temp Theme'         ; . "$MTHEME"            || { Info "missing file " 1 && echo "$MTHEME"  && exit 1 ; } }
LoadProdTheme () { Info ' Load Prod Theme'         ; . "$OTHEME"            || { Info "missing file " 1 && echo "$OTHEME"  && exit 1 ; } }
#  ............................ .........................................#
CopyTempSeed  () { Info ' Copy Temp Seed'          ; cp "$O_SEED" "$M_SEED" || { Info "missing dir  " 1 && echo "$O_SEED"  && exit 1 ; } }
LoadTempSeed  () { Info ' Load Temp Seed'          ; . "$M_SEED"            || { Info "missing file " 1 && echo "$M_SEED"  && exit 1 ; } }
#  ............................ .........................................#
LoadProdSeed  () { Info ' Load Prod Seed'          ; . "$O_SEED"            || { Info "missing file " 1 && echo "$O_SEED"  && exit 1 ; } }
BackupDist    () { Info ' Backup Prod Dist ··' 
  cp "$MXDIST" /tmp/mx_"$(date +%s)" -r                                      || { Info "missing dir  " 1 && echo "$MXDIST"  && exit 1 ; } }
#  ............................ .........................................#
################################
# ////////////////////////////  
# .........
. "$XANSI"
. "$XGENC"
. "$CALIB"
. "$XSNAP"
# .........
SourcePlugs () { for plug in "$MXBASE"/plugins/*.sh; do . "$plug"; done; }
# ............................  
# ............................  
# ##############################
# ////////////////////////////  
Demo () {
  # fillHead "${MXNAME}"; pl '-'
  # Demo_card
  # Demo_slant
  # Demo_shades3
  Demo_block
  Demo_dot
  MXDotLine
  fillCols
}
DemoAll () {
  Demo_card
  Demo_slant
  Demo_shades3
  Demo_shades4

  Demo_dot_slant
  MXDotLine
  fillCols
}

LoadPreview () { CopyTempSeed ; LoadTempTheme ; apply_tmux ; }
DemoLive    () { apply_tmux ; Demo ; }
Revert () {
  ClearTemp
  CopyTempSeed
  UpdatePalette
  DemoLive
}

ApplyPlugs () {
  BackupDist

  Demo
  PressToContinue

  ReleaseSeed
  ReleaseTheme

  for plug_path in "$MXBASE"/plugins/*.sh; do
    local apply_plug; apply_plug="apply_$(basename "$plug_path" | cut -d'-' -f2 | cut -d'.' -f1)"
    "$apply_plug"
  done
}

ReGenerate () {
  UpdatePalette 

  SourcePlugs
  ApplyPlugs
} # ............................ #
Randomize () {
  GeneratePalette

  apply_tmux
  Demo

  PrompRand
  case $REPLY in
    k ) Info 'Keeping draft ·'; SaveAll    ;;
    u ) Info 'Proceeding ····'; ReGenerate ;;
    n ) Info 'Again ·········'; Randomize  ;;
    d ) Info 'Full Demo ·····'; DemoAll    ;;
    * ) Info 'Reverting ·····'; Revert     ;;
  esac

  mlg "━✔━━━┛"
} # ............................ #
{
  mlg "━━━━<XOPT>━━┓"
  menu="$1"; shift; XOPT="$*"; export XOPT
  mlg "━✔━━<XOPT>━━ ${XOPT}"
}
# ............................ #
{
  mlg "━━━━<MENU>━━┓"
  case $menu in
    -r | --generate    ) Randomize     ;;
    -u | --update      ) ReGenerate      ;;
    -U | --update-full ) XOPT+='full'; ReGenerate      ;;
    -d | --demo        ) Demo ;;
    -D | --demo-full   ) DemoAll ;;
    -i | --init        ) LoadPreview; Demo_block ;;
    -l | list          ) ListSnapshots ;;
    -x                 ) XP ;;
    -s | save          ) SaveSnapshot ;;
    *                  ) MXIntro;  exit ;;
  esac
  mlg "━✔━━<MENU>━━┛"
}
# ............................ #

MXDotLine
exit 0

# //////////////////////////// #
################################

