-- $MXC_V · $MXNAME 

local colors = {
  bg = "${XBG}",
  fg = "${XFG}",
  -- yellow = "${CX3}",
  -- cyan = "${CX6}",
  darkblue = "${CX4}",
  -- green = "${CX2}",
  -- orange = "${SBG}",
  violet  = "${C13}",
  magenta  = "${C05}",
  blue = "${C04}",
  red = "${CX1}",
  white = "${C15}",
  darker_black =  "${DK1}",
  black = "${C00}", --  nvim bg
  black2 = "${DL1}",
  one_bg = "${DK3}", -- real bg of onedark
  one_bg2 = "${DL2}",
  one_bg3 = "${DL3}",
  grey = "${C08}",
  grey_fg = "${C07}",
  grey_fg2 = "${DL4}",
  light_grey = "${DL6}",
  baby_pink = "${C11}",
  pink = "${CX1}",
  line = "${SBG}", -- for lines like vertsplit
  green = "${C02}",
  vibrant_green = "${C12}",
  nord_blue = "${SBG}",
  yellow = "${C03}",
  sun = "${CX3}",
  purple = "${C13}",
  dark_purple = "${C05}",
  teal = "${SBG}",
  orange = "${EBG}",
  cyan = "${C06}",

  statusline_bg = "${DK0}",
  statusline_fg = "${SBG}",

  -- statusline_bg = "${DK3}",
  lightbg = "${DL1}",
  lightbg2 = "${DK1}",
  --
  -- #########
  cx1 = "$CX1",
  cx2 = "$CX2",
  cx3 = "$CX3",
  cx4 = "$CX4",
  cx5 = "$CX5",
  cx6 = "$CX6",
  -- #########
  cy1 = "$CY1",
  cy2 = "$CY2",
  cy3 = "$CY3",
  cy4 = "$CY4",
  cy5 = "$CY5",
  cy6 = "$CY6",
  --
  c00 = "$C00",
  c01 = "$C01",
  c02 = "$C02",
  c03 = "$C03",
  c04 = "$C04",
  c05 = "$C05",
  c06 = "$C06",
  c07 = "$C07",
  c08 = "$C08",
  c09 = "$C09",
  c10 = "$C10",
  c11 = "$C11",
  c12 = "$C12",
  c13 = "$C13",
  c14 = "$C14",
  c15 = "$C15",

  sbg = "$SBG",
  sfg = "$SFG",
  wbg = "$WBG",
  wfg = "$WFG",
  ebg = "$EBG",
  efg = "$EFG",
  xbg = "$XBG",
  xfg = "$XFG",
  obg = "$OBG",
  ofg = "$OFG",
  wbx = "$WBX",
  wfx = "$WFX",

  dk0 = "$DK0",
  dk1 = "$DK1",
  dk2 = "$DK2",
  dk3 = "$DK3",
  dk4 = "$DK4",
  dk5 = "$DK5",
  dk6 = "$DK6",
  dk7 = "$DK7",
  dk8 = "$DK8",
  dk9 = "$DK9",

  dl0 = "$DL0",
  dl1 = "$DL1",
  dl2 = "$DL2",
  dl3 = "$DL3",
  dl4 = "$DL4",
  dl5 = "$DL5",
  dl6 = "$DL6",
  dl7 = "$DL7",
  dl8 = "$DL8",
  dl9 = "$DL9",

  lk0 = "$LK0",
  lk1 = "$LK1",
  lk2 = "$LK2",
  lk3 = "$LK3",
  lk4 = "$LK4",
  lk5 = "$LK5",
  lk6 = "$LK6",
  lk7 = "$LK7",
  lk8 = "$LK8",
  lk9 = "$LK9"
}

return colors
