-- $MXC_V · $MXNAME 

local colors = {
  bg = "${XBG}",
  fg = "${XFG}",
  -- yellow = "${CX3}",
  -- cyan = "${CX6}",
  darkblue = "${CX4}",
  -- green = "${CX2}",
  -- orange = "${SBG}",
  violet  = "${C13}",
  magenta  = "${C05}",
  blue = "${C04}",
  red = "${CX1}",
  white = "${C15}",
  darker_black =  "${SK1}",
  black = "${C00}", --  nvim bg
  black2 = "${WK1}",
  one_bg = "${SK3}", -- real bg of onedark
  one_bg2 = "${WK2}",
  one_bg3 = "${WK3}",
  grey = "${C08}",
  grey_fg = "${C07}",
  grey_fg2 = "${WK4}",
  light_grey = "${WK6}",
  baby_pink = "${C11}",
  pink = "${CX1}",
  line = "${SBG}", -- for lines like vertsplit
  green = "${C02}",
  vibrant_green = "${C12}",
  nord_blue = "${SBG}",
  yellow = "${C03}",
  sun = "${CX3}",
  purple = "${C13}",
  dark_purple = "${C05}",
  teal = "${SBG}",
  orange = "${EBG}",
  cyan = "${C06}",

  statusline_bg = "${SK0}",
  statusline_fg = "${SBG}",

  -- statusline_bg = "${SK3}",
  lightbg = "${WK1}",
  lightbg2 = "${SK1}",
  --
  fullblack = "#000000",
  -- #########
  cx1 = "$CX1",
  cx2 = "$CX2",
  cx3 = "$CX3",
  cx4 = "$CX4",
  cx5 = "$CX5",
  cx6 = "$CX6",
  --
  cy1 = "$CY1",
  cy2 = "$CY2",
  cy3 = "$CY3",
  cy4 = "$CY4",
  cy5 = "$CY5",
  cy6 = "$CY6",
  --
  cf1 = "$CF1",
  cf2 = "$CF2",
  cf3 = "$CF3",
  cf4 = "$CF4",
  cf5 = "$CF5",
  cf6 = "$CF6",
  --
  c00 = "$C00",
  c01 = "$C01",
  c02 = "$C02",
  c03 = "$C03",
  c04 = "$C04",
  c05 = "$C05",
  c06 = "$C06",
  c07 = "$C07",
  c08 = "$C08",
  c09 = "$C09",
  c10 = "$C10",
  c11 = "$C11",
  c12 = "$C12",
  c13 = "$C13",
  c14 = "$C14",
  c15 = "$C15",

  sbg = "$SBG",
  sfg = "$SFG",
  wbg = "$WBG",
  wfg = "$WFG",
  ebg = "$EBG",
  efg = "$EFG",
  xbg = "$XBG",
  xfg = "$XFG",
  obg = "$OBG",
  ofg = "$OFG",
  wbx = "$WBX",
  wfx = "$WFX",

  sk0 = "$SK0",
  sk1 = "$SK1",
  sk2 = "$SK2",
  sk3 = "$SK3",
  sk4 = "$SK4",
  sk5 = "$SK5",
  sk6 = "$SK6",
  sk7 = "$SK7",
  sk8 = "$SK8",
  sk9 = "$SK9",

  wk0 = "$WK0",
  wk1 = "$WK1",
  wk2 = "$WK2",
  wk3 = "$WK3",
  wk4 = "$WK4",
  wk5 = "$WK5",
  wk6 = "$WK6",
  wk7 = "$WK7",
  wk8 = "$WK8",
  wk9 = "$WK9",

  ek0 = "$EK0",
  ek1 = "$EK1",
  ek2 = "$EK2",
  ek3 = "$EK3",
  ek4 = "$EK4",
  ek5 = "$EK5",
  ek6 = "$EK6",
  ek7 = "$EK7",
  ek8 = "$EK8",
  ek9 = "$EK9"
}

return colors
